Add feature to change the color for each tags
xhacker/TagListView pull request #237
Opened 2019-08-25 22:58 UTC by nator333

- Add UIColor argument for the constructors

2019-10-01 22:52 UTC, Dfmarulanda commented
How is this going?

2019-10-13 11:47 UTC, xhacker requested changes
Thanks for the pr! I have some minor comments.

2019-10-13 11:47 UTC, xhacker commented on TagListView/TagListView.swift
> +    private func createNewTagView(_ title: String, _ backgroundColor: UIColor? = nil) -> TagView {
Can you keep the named argument `backgroundColor` here? I think it increases readability.

2019-10-13 11:47 UTC, xhacker commented on TagListView/TagListView.swift
> +    open func addTag(_ title: String, _ backgroundColor: UIColor? = nil) -> TagView {
Same. Please keep `backgroundColor`.

2019-10-13 11:47 UTC, xhacker commented on TagListView/TagListView.swift
> +    open func addTags(titleWithColors: [String : UIColor]) -> [TagView] {
Can you add some documentation for this in README?

2019-10-13 17:55 UTC, nator333 commented on TagListView/TagListView.swift
> +    private func createNewTagView(_ title: String, _ backgroundColor: UIColor? = nil) -> TagView {
468738af5d661e3d56e7709da86f9993f6bc1590

2019-10-13 17:55 UTC, nator333 commented on TagListView/TagListView.swift
> +    open func addTag(_ title: String, _ backgroundColor: UIColor? = nil) -> TagView {
468738af5d661e3d56e7709da86f9993f6bc1590

2019-10-13 17:56 UTC, nator333 commented on TagListView/TagListView.swift
> +    open func addTags(titleWithColors: [String : UIColor]) -> [TagView] {
Please give me advice if you think of anything for the improvement.
293fa1475b2581a94fabd7a34ffae40f6caa05d0

2019-10-14 20:58 UTC, Cee requested changes

2019-10-14 20:58 UTC, Cee commented on TagListView/TagListView.swift
> +
I'd prefer to write as `tagView.tagBackgroundColor = backgroundColor ?? tagBackgroundColor`.

2019-10-14 20:58 UTC, Cee commented on TagListView/TagListView.swift
> +    open func addTag(_ title: String, withBgColor backgroundColor: UIColor? = nil) -> TagView {
Same here.

2019-10-14 20:58 UTC, Cee commented on TagListView/TagListView.swift
> +    private func createNewTagView(_ title: String, withBgColor backgroundColor: UIColor? = nil) -> TagView {
Can you replace `withBgColor` with `withBackgroundColor`?

2019-10-14 20:58 UTC, Cee commented on TagListView/TagListView.swift
> +
Also if you introduced background color to each tag, it would be a little bit vague to mention `tagBackgroundColor` here. I'd prefer to rename it as `defaultBackgroundColor`.

2019-10-14 22:22 UTC, nator333 commented on TagListView/TagListView.swift
> +    private func createNewTagView(_ title: String, withBgColor backgroundColor: UIColor? = nil) -> TagView {
Thanks for the comment!
Replacing the name is easy, but why?

2019-10-15 01:34 UTC, xhacker commented on TagListView/TagListView.swift
> +    private func createNewTagView(_ title: String, withBgColor backgroundColor: UIColor? = nil) -> TagView {
or simply `backgroundColor`.

2019-10-15 01:34 UTC, xhacker commented on TagListView/TagListView.swift
> +
Will renaming break existing code? If so, I’d suggest keeping the old name.

2019-10-15 01:37 UTC, nator333 commented on TagListView/TagListView.swift
> +
> Will renaming break existing code? If so, I’d suggest keeping the old name.

Yup, that could happen.

2019-10-15 01:41 UTC, nator333 commented on TagListView/TagListView.swift
> +    private func createNewTagView(_ title: String, withBgColor backgroundColor: UIColor? = nil) -> TagView {
I prefer 'with' because it makes more sense.

2019-10-16 00:00 UTC, Cee commented on TagListView/TagListView.swift
> +    private func createNewTagView(_ title: String, withBgColor backgroundColor: UIColor? = nil) -> TagView {
LGTM. I would like to remove `with` if the parameter is not in the first place.

Example: `createNewTagView(_ title: String, backgroundColor: UIColor)`

2024-08-07 21:13 UTC, closed without merging